sudo: required
language: node_js
node_js: '12'

services:
  - docker

before_deploy:
  - npm install
  - CI=false npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket: yummeal.ai
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  local_dir: build
  wait_until_deployed: true

  on: 
    branch: main